# Generated by Django 2.1.1 on 2018-09-04 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete='models.CASCADE', related_name='invitation_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete='models.CASCADE', related_name='invitations_recieved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
