# Generated by Django 2.1.1 on 2018-09-05 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, help_text='Its always nice to add a friendly message!', max_length=300, verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select the user you want to play with', on_delete='models.CASCADE', related_name='invitations_recieved', to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
